#' Query WikiAves for bird media metadata
#'
#' @description
#' `query_wikiaves` searches for metadata from
#' [WikiAves](https://www.wikiaves.com.br), a Brazilian citizen-science
#' platform and the largest birdwatching community in the country. It
#' functions as a collaborative, interactive encyclopedia of Brazilian
#' birds, where users contribute georeferenced photographs and sound
#' recordings that build a large database used for research and
#' conservation. `query_wikiaves` returns metadata for image or sound
#' recordings matching a given species, including download links,
#' locality, author, and verification status.
#'
#' WikiAves sits behind Cloudflare's bot protection, so this function
#' requires authentication, which is done with [access_wikiaves()] (see
#' Examples).
#'
#' @param species Character string giving the scientific name of the
#'   species to search for (e.g. `"Procnias averano"`). Defaults to
#'   `getOption("suwo_species")`.
#' @param format Character string, either `"image"` or `"sound"`,
#'   indicating which type of media to query. Defaults to
#'   `getOption("suwo_format", c("image", "sound"))`.
#' @param cores Numeric. Number of cores to use for parallel processing of
#'   paginated results. Defaults to `getOption("suwo_cores", 1)`.
#' @param pb Logical. Whether to show a progress bar. Defaults to
#'   `getOption("suwo_pb", TRUE)`.
#' @param verbose Logical. Whether to print progress and error messages.
#'   Defaults to `getOption("suwo_verbose", TRUE)`.
#' @param all_data Logical. Whether to return all available columns rather
#'   than the standard `suwo` output columns. Defaults to
#'   `getOption("suwo_all_data", FALSE)`.
#' @param raw_data Logical. Whether to return the raw, unformatted query
#'   output instead of the standardized `suwo` output. Defaults to
#'   `getOption("suwo_raw_data", FALSE)`.
#' @param cookies Single character string of WikiAves authentication
#'   credentials, used to get past Cloudflare's bot protection on every
#'   request this function makes. It is generated by [access_wikiaves()]
#'   and saved as an environmental variable (`Sys.getenv("wikiaves_cookies")`),
#'   which is read by default by `query_wikiaves`.
#'
#' @details
#' WikiAves sits behind Cloudflare's bot protection, so `cookies` must be
#' a valid, non-expired credentials string -- see **Do I need to obtain
#' new credentials before every call?** below.
#'
#' **Do I need to obtain new credentials before every call?** No -- only
#' once per Cloudflare session. The `cf_clearance` cookie returned by
#' [access_wikiaves()] is typically valid for roughly an hour (Cloudflare
#' does not publish an exact figure, and the duration can vary); after
#' that, requests made with it will start failing again with an HTTP 403,
#' and [access_wikiaves()] simply needs to be called again to obtain a
#' fresh set of credentials.
#'
#' A few practical notes on when to refresh credentials:
#' - If `query_wikiaves` is paging through a species with a large number
#'   of recordings, the session may expire partway through a single call
#'   -- if that happens, call [access_wikiaves()] again and retry.
#' - If some time has passed since the cookies were last obtained, refresh
#'   them before querying rather than waiting for a failure.
#' - [access_wikiaves()] reuses the same browser profile directory by
#'   default, so repeat calls are usually fast and do not require solving
#'   the Cloudflare challenge by hand each time.
#'
#' If valid cookies are not supplied, `query_wikiaves` fails gracefully
#' with an explanatory message and returns `invisible(NULL)` rather than
#' throwing an error.
#'
#' @return
#' A data frame of WikiAves observations matching `species` and `format`,
#' with standardized `suwo` columns (or all available columns if
#' `all_data = TRUE`, or the raw query output if `raw_data = TRUE`).
#' Returns `invisible(NULL)` if the species is not found, no matching
#' records exist, or the query otherwise fails.
#'
#' @seealso [access_wikiaves()], which generates the `cookies` argument
#'   this function requires.
#'
#' @examples
#' if (interactive()) {
#' # Obtain fresh authentication cookies (only needs to be re-run once the
#' # cookies expire, roughly every hour):
#' cookies_live <- access_wikiaves()
#'
#' # Query sound recordings for a species:
#' result <- query_wikiaves(
#'   species = "Procnias averano",
#'   format = "sound",
#'   cookies = cookies_live
#' )
#'
#' # Query image records instead:
#' result_images <- query_wikiaves(
#'   species = "Procnias averano",
#'   format = "image",
#'   cookies = cookies_live
#' )
#' }
#'
#' @export
query_wikiaves <-
  function(
    species = getOption("suwo_species"),
    format = getOption("suwo_format", c("image", "sound")),
    cores = getOption("suwo_cores", 1),
    pb = getOption("suwo_pb", TRUE),
    verbose = getOption("suwo_verbose", TRUE),
    all_data = getOption("suwo_all_data", FALSE),
    raw_data = getOption("suwo_raw_data", FALSE),
    cookies = Sys.getenv("wikiaves_cookies")
  ) {
    ##  argument checking
    check_results <- .check_arguments(
      fun = "query_wikiaves",
      args = list(
        species = species,
        format = format,
        cores = cores,
        pb = pb,
        verbose = verbose,
        all_data = all_data,
        raw_data = raw_data
      )
    )

    # report errors
    .report_assertions(check_results)

    # Use the unified connection checker. Note .checkconnection() treats an
    # HTTP 403 from WikiAves as "connected" rather than "down", since
    # Cloudflare blocks plain requests with a 403 even when the site is
    # perfectly healthy -- see .checkconnection() for details.
    if (!.checkconnection(verb = verbose, service = "wikiaves")) {
      return(invisible(NULL))
    }

    # assign a value to format
    format <- rlang::arg_match(format, values = c("image", "sound"))

    wiki_format <- switch(format, sound = "s", image = "f")

    # parse the single JSON cookies string produced by access_wikiaves()
    # into a named vector, then split the browser UA out of it (see
    # .parse_wikiaves_cookies() in internal_functions.R)
    cookies_parsed <- .parse_wikiaves_cookies(cookies)

    # No cookies were provided at all (e.g. `cookies` is empty/unset and
    # the wikiaves_cookies environment variable was never populated by
    # access_wikiaves() -- as is expected on CI/CRAN check machines, which
    # cannot launch a browser). Fail gracefully with a clear, actionable
    # message rather than crashing on missing-name lookups below.
    if (
      length(cookies_parsed) == 0 || !("browser_ua" %in% names(cookies_parsed))
    ) {
      if (verbose) {
        .message(
          text = paste(
            "No WikiAves authentication cookies were provided.",
            "Run access_wikiaves() first (see ?access_wikiaves), then",
            "either pass its result via the `cookies` argument or, by",
            "default, it is stored automatically for this session."
          ),
          as = "failure"
        )
      }
      return(invisible(NULL))
    }

    # The remainder of this function makes real network requests to
    # WikiAves. Building the request and handling a failed/rejected first
    # response (e.g. HTTP 403 from expired or invalid cookies) does NOT
    # require *valid* credentials -- any syntactically valid cookies
    # string plus real internet access is enough to exercise this part,
    # since Cloudflare will reject bad credentials with a 403 regardless.
    # Only a genuinely *successful* response (needing real, current
    # WikiAves cookies) is required past that point, which is where the
    # nocov boundary below actually starts -- see test_query_wikiaves.R
    # for both the fake-cookies/expect-403 test (runs on ordinary CI) and
    # the real-cookies tests (skipped unless a live wikiaves_cookies
    # session is available).

    # use `[` (not `[[`) for browser_ua too: `[[` throws if the name is
    # missing, `[` returns NA -- already validated above, but this keeps
    # the extraction itself safe against any future changes to the check
    browser_ua <- unname(cookies_parsed["browser_ua"])
    cookie_vec <- cookies_parsed[names(cookies_parsed) != "browser_ua"]

    # helper to build a request with the shared UA / headers / cookies,
    # matching probe_wikiaves_debug
    .wikiaves_request <- function(url) {
      req <- httr2::request(url)
      req <- httr2::req_user_agent(req, browser_ua)
      req <- httr2::req_headers(
        req,
        Accept = "application/json, text/plain, */*",
        Referer = "https://www.wikiaves.com.br/",
        `Accept-Language` = "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"
      )

      if (length(cookie_vec) > 0) {
        req <- do.call(
          httr2::req_cookies_set,
          c(list(req), as.list(cookie_vec))
        )
      }

      req
    }
    # -------------------------------------------------------------------------

    # initialize search with user agent
    request_obj <- .wikiaves_request(
      "https://www.wikiaves.com.br/getTaxonsJSON.php"
    )

    request_obj <- httr2::req_url_query(
      request_obj,
      term = species
    )

    # do not auto-throw on 4xx/5xx -- a 403 here most likely means the
    # cookies passed via `cookies` are stale/invalid (see access_wikiaves()),
    # and should be reported via the friendly failure message below rather
    # than as an uncaught httr2 error
    request_obj <- httr2::req_error(
      request_obj,
      is_error = function(resp) FALSE
    )

    response <- httr2::req_perform(request_obj)

    # check if request succeeded
    if (httr2::resp_status(response) >= 400) {
      if (verbose) {
        .message(
          text = paste0(
            "Wikiaves query request failed: ",
            httr2::resp_status_desc(response),
            " (HTTP ",
            httr2::resp_status(response),
            "). ",
            "Cookies may have expired -- try running access_wikiaves() again."
          ),
          as = "failure"
        )
      }
      return(invisible(NULL))
    }

    # ---- everything below this point requires a genuinely successful
    # (200) response, i.e. real, current, valid WikiAves cookies -- not
    # reachable in CI/CRAN checks (see test_query_wikiaves.R, which skips
    # unless a real wikiaves_cookies session is available)
    # nocov start

    get_ids <- httr2::resp_body_json(
      response,
      check_type = FALSE,
      simplifyVector = TRUE,
      simplifyDataFrame = TRUE
    )

    # do exact matching for species name
    if (length(get_ids) > 1) {
      get_ids <- get_ids[
        trimws(tolower(get_ids$label)) == trimws(tolower(species)),
      ]
    }

    if (length(get_ids) == 0) {
      if (verbose) {
        .message("Search species not found", as = "failure")
      }
      return(invisible(NULL))
    }

    get_ids$total_registers <- vapply(
      seq_len(nrow(get_ids)),
      function(u) {
        request_obj <- .wikiaves_request(
          "https://www.wikiaves.com.br/getRegistrosJSON.php"
        )

        request_obj <- httr2::req_url_query(
          request_obj,
          tm = wiki_format,
          t = "s",
          s = get_ids$id[u],
          o = "mp",
          p = 1
        )

        request_obj <- httr2::req_error(request_obj, is_error = function(resp) {
          FALSE
        })

        response <- try(httr2::req_perform(request_obj), silent = TRUE)

        # if fail request return -9999
        if (.is_error(response)) {
          return(-999)
        }

        # check if request succeeded
        if (httr2::resp_is_error(response)) {
          return(-999)
        }

        content <- httr2::resp_body_json(response)
        as.numeric(content$registros$total)
      },
      numeric(1)
    )

    # let user gracefully know error when downloading metadata
    if (
      any(vapply(
        get_ids$total_registers,
        function(x) x == -999,
        FUN.VALUE = logical(1)
      ))
    ) {
      if (verbose) {
        .message(text = "Metadata could not be downloaded", as = "failure")
      }
      return(invisible(NULL))
    }

    if (sum(get_ids$total_registers) == 0) {
      if (verbose) {
        .message(text = "No matching records found", as = "failure")
      }
      return(invisible(NULL))
    }

    # get number of pages (20 is the default number of registers per page)
    get_ids$pages <- ceiling(get_ids$total_registers / 20)

    # remove those rows with no pages
    # (only needed when many species are returned)
    get_ids <- get_ids[get_ids$pages > 0, ]

    id_by_page_list <- lapply(seq_len(nrow(get_ids)), function(x) {
      X <- get_ids[x, ]
      data.frame(id = X$id, page = 1:X$pages)
    })

    id_by_page_df <- do.call(rbind, id_by_page_list)

    # search recs in wikiaves (results are returned in pages with 500
    # recordings each)
    if (verbose) {
      .message(n = get_ids$total_registers[1], as = "success")
    }

    # loop over pages
    query_output_list <- .pbapply_sw(
      X = seq_len(nrow(id_by_page_df)),
      cl = cores,
      pbar = pb,
      function(x, Y = seq_len(nrow(id_by_page_df))) {
        # set index to get the right offset
        i <- Y[x]

        # wait avoid overloading the server
        # **INTERVARLS < 1s BRAKE THE FUNCTION**
        Sys.sleep(1)

        request_obj <- .wikiaves_request(
          "https://www.wikiaves.com.br/getRegistrosJSON.php"
        )

        request_obj <- httr2::req_url_query(
          request_obj,
          tm = wiki_format,
          t = "s",
          s = id_by_page_df$id[i],
          o = "mp",
          p = id_by_page_df$page[i]
        )

        # do not auto-throw so we can retry manually
        request_obj <- httr2::req_error(
          request_obj,
          is_error = function(resp) FALSE
        )

        response <- httr2::req_perform(request_obj)

        # retry once if request failed
        if (httr2::resp_is_error(response)) {
          Sys.sleep(1)

          response <- httr2::req_perform(request_obj)
        }

        # if still failing, stop here (no downstream code runs)
        if (httr2::resp_is_error(response)) {
          rlang::abort(
            paste(
              "WikiAves request failed:",
              httr2::resp_status(response),
              httr2::resp_status_desc(response)
            ),
            class = "wikiaves_request_error"
          )
        }

        # parse JSON only if request succeeded
        query_output <-
          httr2::resp_body_json(
            response,
            simplifyVector = TRUE
          )

        # make it a data frame
        output_df <-
          as.data.frame(do.call(
            rbind,
            lapply(
              query_output$registros$itens,
              unlist
            )
          ))

        # fix link
        output_df$link <- gsub("#", "", as.character(output_df$link))

        return(output_df)
      }
    )

    # let user know error when downloading metadata
    if (any(vapply(query_output_list, .is_error, FUN.VALUE = logical(1)))) {
      if (verbose) {
        .message(text = "Metadata could not be downloaded", as = "failure")
      }
      return(invisible(NULL))
    }

    # combine into a single data frame
    query_output_df <- .merge_data_frames(query_output_list)

    # rename rows
    rownames(query_output_df) <- seq_len(nrow(query_output_df))

    # change jpg to mp3 in links
    if (format == "sound") {
      query_output_df$link <-
        gsub(".jpg$", ".mp3", query_output_df$link)
    }

    # remove weird columns
    query_output_df$por <- query_output_df$grande <-
      query_output_df$enviado <- NULL

    # verified?
    query_output_df$is_questionada <-
      as.logical(query_output_df$is_questionada)

    # make NAs observations with no link
    query_output_df$link[grepl("^\\d+$", query_output_df$link)] <- NA

    # add file format
    # query_output_df$format <- format
    query_output_df$country <- "Brazil"

    query_output_df$observation_url <- paste0(
      "https://www.wikiaves.com.br/",
      query_output_df$id
    )

    # rename output columns
    query_output_df <- .format_query_output(
      X = query_output_df,
      call = base::match.call(),
      column_names = c(
        "id" = "key",
        "tipo" = "format",
        "id_usuario" = "user.id",
        "sp.id" = "species_id",
        "sp.nome" = "species",
        "sp.nvt" = "common.name",
        "sp.idwiki" = "repository.id",
        "autor" = "author",
        "perfil" = "user_name",
        "data" = "date",
        "is_questionada" = "verified",
        "local" = "locality",
        "idMunicipio" = "locality.id",
        "coms" = "number_of_comments",
        "likes" = "likes",
        "vis" = "visualizations",
        "link" = "file_url",
        "dura" = "duration",
        "scientific.name" = "species",
        # "species_id" = "species_code",
        "autor" = "user_name"
      ),
      all_data = all_data,
      format = format,
      raw_data = raw_data
    )

    return(query_output_df)
    # nocov end
  }
